INSERT  INTO `menu`(`id`,`description`,`name`) VALUES (1,'floor','floor'),
(2,'room','room'),
(3,'materiel','materiel'),
(4,'inventory','inventory'),
(5,'role','role'),
(6,'staff','staff'),
(7,'leave','leave'),
(8,'finance','finance'),
(9,'report','report'),
(10,'notify','notify'),
(11,'hotel_info','hotel_info'),
(12,'settings','settings');
